# Tomcat
server:
  port: 9202

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-gen
  profiles:
    # 环境配置
    active: @profiles.active@

---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  cloud:
    stream:
      function:
        # 重点配置 与 binding 名与消费者对应
        definition: delay
      rabbit:
        bindings:
          delay-in-0:
            consumer:
              delayedExchange: true
          delay-out-0:
            producer:
              delayedExchange: true
      bindings:
        delay-in-0:
          destination: delay.exchange.cloud
          content-type: application/json
          group: delay-group
          binder: rabbit
        delay-out-0:
          destination: delay.exchange.cloud
          content-type: application/json
          group: delay-group
          binder: rabbit

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
